name: Begin Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  post_all_job:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.RGHASO_TOKEN }}
        repository: ${{ github.repository }}
        event-type: trigger-workflow-1
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
