name: Update Website Information

on:
  workflow_dispatch:

  repository_dispatch:
    types: [trigger-workflow-1]

jobs:
  update_info:
    runs-on: ubuntu-latest
    steps:
    - name: Initial setup
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run the data changing script
      run: python3 .github/workflows/FOR_GITHUB_ACTION_ONLY.py --verbose

    - name: Setup credential for commit
      run: |
        git config --local user.name "QuanMCPC"
        git config --local user.email "60545346+QuanMCPC@users.noreply.github.com"

    - name: Staged file for commit
      run: git add .

    - name: Commit file
      run: git commit -m "Update website's information"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

  post_all_job:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [update_info]
    steps:
    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.RGHASO_TOKEN }}
        repository: ${{ github.repository }}
        event-type: trigger-workflow-2
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
